# Generated by Django 5.1.4 on 2026-06-15 14:27

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="erstellt am"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="geändert am"),
                ),
                (
                    "number",
                    models.CharField(
                        max_length=40, unique=True, verbose_name="Rechnungsnummer"
                    ),
                ),
                (
                    "sequence",
                    models.PositiveIntegerField(verbose_name="laufende Nummer"),
                ),
                ("invoice_date", models.DateField(verbose_name="Rechnungsdatum")),
                (
                    "period_start",
                    models.DateField(verbose_name="Leistungszeitraum von"),
                ),
                ("period_end", models.DateField(verbose_name="Leistungszeitraum bis")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Entwurf"),
                            ("finalized", "Festgeschrieben"),
                            ("cancelled", "Storniert"),
                        ],
                        default="draft",
                        max_length=12,
                        verbose_name="Status",
                    ),
                ),
                (
                    "subtotal_net",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=12,
                        verbose_name="Zwischensumme netto",
                    ),
                ),
                (
                    "vat_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("19"),
                        max_digits=5,
                        verbose_name="USt-Satz (%)",
                    ),
                ),
                (
                    "vat_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=12,
                        verbose_name="USt-Betrag",
                    ),
                ),
                (
                    "total_gross",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=12,
                        verbose_name="Gesamtbetrag brutto",
                    ),
                ),
                (
                    "payment_term_days",
                    models.PositiveSmallIntegerField(
                        default=14, verbose_name="Zahlungsziel (Tage)"
                    ),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True, null=True, upload_to="invoices/", verbose_name="PDF"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_invoices",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="erstellt von",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to="customers.customer",
                        verbose_name="Kunde",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rechnung",
                "verbose_name_plural": "Rechnungen",
                "ordering": ("-invoice_date", "-sequence"),
            },
        ),
        migrations.CreateModel(
            name="InvoiceLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.PositiveSmallIntegerField(verbose_name="Position")),
                (
                    "line_type",
                    models.CharField(
                        choices=[
                            ("base_hours", "Netto Stunden ohne Pausen"),
                            ("night", "Nachtarbeit Zuschlag"),
                            ("saturday", "Samstag Zuschlag"),
                            ("sunday", "Sonntag Zuschlag"),
                            ("holiday", "Feiertag Zuschlag"),
                            ("special", "Spezialzuschlag"),
                            ("travel", "Fahrkosten"),
                        ],
                        max_length=12,
                        verbose_name="Typ",
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=200, verbose_name="Bezeichnung"),
                ),
                (
                    "quantity_hours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="Bezahlt (Std.)",
                    ),
                ),
                (
                    "factor",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Faktor (€)",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=12,
                        verbose_name="Betrag (€)",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="invoicing.invoice",
                        verbose_name="Rechnung",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rechnungsposition",
                "verbose_name_plural": "Rechnungspositionen",
                "ordering": ("invoice", "position"),
            },
        ),
    ]
