# Generated by Django 5.1.4 on 2026-06-15 15:51

import apps.invoicing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoicing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="pdf_file",
            field=models.FileField(
                blank=True,
                null=True,
                storage=apps.invoicing.models.invoice_pdf_storage,
                upload_to="",
                verbose_name="PDF",
            ),
        ),
    ]
