# Generated by Django 5.1.4 on 2026-06-15 21:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_alter_customer_organization'),
        ('invoicing', '0004_alter_invoice_organization'),
        ('organizations', '0002_default_org_and_backfill'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='number',
            field=models.CharField(max_length=40, verbose_name='Rechnungsnummer'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(fields=('organization', 'number'), name='unique_org_invoice_number'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(fields=('organization', 'sequence'), name='unique_org_invoice_sequence'),
        ),
    ]
