# Generated by Django 5.1.4 on 2026-06-16 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0005_alter_invoice_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='versendet am'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Entwurf'), ('finalized', 'Festgeschrieben'), ('sent', 'Versendet'), ('cancelled', 'Storniert')], default='draft', max_length=12, verbose_name='Status'),
        ),
    ]
