# Generated by Django 5.1.4 on 2026-06-16 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0006_invoice_sent_at_alter_invoice_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='bezahlt am'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Entwurf'), ('finalized', 'Festgeschrieben'), ('sent', 'Versendet'), ('paid', 'Bezahlt'), ('cancelled', 'Storniert')], default='draft', max_length=12, verbose_name='Status'),
        ),
    ]
