# Generated by Django 5.1.4 on 2026-06-16 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0007_invoice_paid_at_alter_invoice_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='last_reminded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='zuletzt gemahnt am'),
        ),
    ]
