# Generated by Django 5.1.4 on 2026-06-16 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0008_invoice_last_reminded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='is_small_business',
            field=models.BooleanField(default=False, help_text='Zum Zeitpunkt der Abrechnung übernommener Kleinunternehmer-Status.', verbose_name='Kleinunternehmer (§ 19 UStG)'),
        ),
    ]
