# Generated by Django 5.1.4 on 2026-06-15 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Erstellt"),
                            ("update", "Geändert"),
                            ("delete", "Gelöscht"),
                            ("submit", "Eingereicht"),
                            ("approve", "Freigegeben"),
                            ("reject", "Abgelehnt"),
                            ("invoice", "Abgerechnet"),
                        ],
                        max_length=20,
                        verbose_name="Aktion",
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(max_length=80, verbose_name="Objekttyp"),
                ),
                (
                    "entity_id",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="Objekt-ID"
                    ),
                ),
                (
                    "summary",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Zusammenfassung"
                    ),
                ),
                (
                    "changes",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Änderungen"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Zeitpunkt"),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_entries",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Akteur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit-Eintrag",
                "verbose_name_plural": "Audit-Log",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["entity_type", "entity_id"],
                        name="common_audi_entity__147a18_idx",
                    ),
                    models.Index(
                        fields=["-created_at"], name="common_audi_created_fa4caf_idx"
                    ),
                ],
            },
        ),
    ]
