# Generated by Django 5.1.4 on 2026-06-15 14:27

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0001_initial"),
        ("invoicing", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Shift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="erstellt am"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="geändert am"),
                ),
                (
                    "shift_type",
                    models.CharField(
                        choices=[
                            ("frueh", "Frühdienst"),
                            ("spaet", "Spätdienst"),
                            ("nacht", "Nachtdienst"),
                        ],
                        max_length=10,
                        verbose_name="Schichtart",
                    ),
                ),
                ("date", models.DateField(verbose_name="Datum")),
                ("start_time", models.TimeField(verbose_name="Startzeit")),
                ("end_time", models.TimeField(verbose_name="Endzeit")),
                (
                    "break_minutes",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Pause (Minuten)"
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="Bemerkung")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Entwurf"),
                            ("submitted", "Eingereicht"),
                            ("approved", "Freigegeben"),
                            ("rejected", "Abgelehnt"),
                            ("invoiced", "Abgerechnet"),
                        ],
                        default="draft",
                        max_length=12,
                        verbose_name="Status",
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="eingereicht am"
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="geprüft am"
                    ),
                ),
                (
                    "correction_reason",
                    models.TextField(
                        blank=True, verbose_name="Korrektur-/Ablehnungsgrund"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_shifts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="erstellt von",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shifts",
                        to="customers.customer",
                        verbose_name="Kunde",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shifts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Mitarbeiter",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        help_text="Verknüpfte Rechnung; verhindert doppelte Abrechnung.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shifts",
                        to="invoicing.invoice",
                        verbose_name="Rechnung",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_shifts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="geprüft von",
                    ),
                ),
            ],
            options={
                "verbose_name": "Schicht",
                "verbose_name_plural": "Schichten",
                "ordering": ("-date", "start_time"),
            },
        ),
        migrations.CreateModel(
            name="ShiftCalculation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="erstellt am"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="geändert am"),
                ),
                (
                    "total_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=6,
                        verbose_name="Gesamtstunden",
                    ),
                ),
                (
                    "break_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=6,
                        verbose_name="Pausenstunden",
                    ),
                ),
                (
                    "paid_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=6,
                        verbose_name="bezahlte Stunden",
                    ),
                ),
                (
                    "night_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=6,
                        verbose_name="Nachtstunden",
                    ),
                ),
                (
                    "saturday_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=6,
                        verbose_name="Samstagstunden",
                    ),
                ),
                (
                    "sunday_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=6,
                        verbose_name="Sonntagstunden",
                    ),
                ),
                (
                    "holiday_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=6,
                        verbose_name="Feiertagstunden",
                    ),
                ),
                (
                    "is_holiday",
                    models.BooleanField(default=False, verbose_name="Feiertag"),
                ),
                (
                    "holiday_name",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Feiertagsname"
                    ),
                ),
                (
                    "base_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=10,
                        verbose_name="Grundbetrag",
                    ),
                ),
                (
                    "night_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=10,
                        verbose_name="Nachtzuschlag",
                    ),
                ),
                (
                    "saturday_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=10,
                        verbose_name="Samstagzuschlag",
                    ),
                ),
                (
                    "sunday_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=10,
                        verbose_name="Sonntagszuschlag",
                    ),
                ),
                (
                    "holiday_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=10,
                        verbose_name="Feiertagszuschlag",
                    ),
                ),
                (
                    "special_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=10,
                        verbose_name="Spezialzuschläge",
                    ),
                ),
                (
                    "travel_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=10,
                        verbose_name="Fahrkosten",
                    ),
                ),
                (
                    "calculated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="berechnet am"
                    ),
                ),
                (
                    "shift",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calculation",
                        to="shifts.shift",
                        verbose_name="Schicht",
                    ),
                ),
            ],
            options={
                "verbose_name": "Schichtberechnung",
                "verbose_name_plural": "Schichtberechnungen",
            },
        ),
        migrations.AddIndex(
            model_name="shift",
            index=models.Index(
                fields=["customer", "status", "date"],
                name="shifts_shif_custome_fb2de7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="shift",
            index=models.Index(
                fields=["employee", "date"], name="shifts_shif_employe_d10d61_idx"
            ),
        ),
    ]
