# Generated by Django 5.1.4 on 2026-06-15 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('shifts', '0002_shift_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shifts', to='organizations.organization', verbose_name='Organisation'),
        ),
    ]
