# Generated by Django 5.1.4 on 2026-06-15 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Zugehörige Organisation. Leer = plattformweiter Superuser.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='organizations.organization', verbose_name='Organisation'),
        ),
    ]
