# Generated by Django 5.1.4 on 2026-06-15 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="erstellt am"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="geändert am"),
                ),
                (
                    "qualification",
                    models.CharField(
                        choices=[
                            ("pflegehilfskraft", "Pflegehilfskraft"),
                            ("pflegefachkraft", "Pflegefachkraft"),
                        ],
                        default="pflegehilfskraft",
                        max_length=20,
                        verbose_name="Qualifikation",
                    ),
                ),
                (
                    "street",
                    models.CharField(blank=True, max_length=200, verbose_name="Straße"),
                ),
                (
                    "zip_code",
                    models.CharField(blank=True, max_length=10, verbose_name="PLZ"),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Wohnort"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="aktiv")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Benutzer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mitarbeiterprofil",
                "verbose_name_plural": "Mitarbeiterprofile",
                "ordering": ("user__last_name", "user__first_name"),
            },
        ),
    ]
