# Generated by Django 5.1.4 on 2026-06-15 14:27

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="erstellt am"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="geändert am"),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Name / Einrichtung"),
                ),
                (
                    "customer_number",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="Kundennummer"
                    ),
                ),
                (
                    "contact_person",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Ansprechpartner"
                    ),
                ),
                (
                    "street",
                    models.CharField(blank=True, max_length=200, verbose_name="Straße"),
                ),
                (
                    "zip_code",
                    models.CharField(blank=True, max_length=10, verbose_name="PLZ"),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=120, verbose_name="Ort"),
                ),
                (
                    "bundesland",
                    models.CharField(
                        choices=[("HE", "Hessen"), ("RP", "Rheinland-Pfalz")],
                        help_text="Steuert die Feiertagslogik.",
                        max_length=2,
                        verbose_name="Bundesland",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="Telefonnummer"
                    ),
                ),
                (
                    "fax",
                    models.CharField(blank=True, max_length=40, verbose_name="Fax"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="E-Mail-Adresse"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="aktiv")),
            ],
            options={
                "verbose_name": "Kunde",
                "verbose_name_plural": "Kunden",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="CustomerContract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="erstellt am"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="geändert am"),
                ),
                ("valid_from", models.DateField(verbose_name="gültig ab")),
                ("is_active", models.BooleanField(default=True, verbose_name="aktiv")),
                (
                    "base_hourly_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Basis für Grundstunden und prozentuale Zuschläge.",
                        max_digits=8,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="Kundenstundensatz (€)",
                    ),
                ),
                (
                    "night_surcharge_pct",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("25"),
                        max_digits=5,
                        verbose_name="Nachtzuschlag (%)",
                    ),
                ),
                (
                    "saturday_surcharge_pct",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("25"),
                        max_digits=5,
                        verbose_name="Samstagzuschlag (%)",
                    ),
                ),
                (
                    "sunday_surcharge_pct",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("50"),
                        max_digits=5,
                        verbose_name="Sonntagszuschlag (%)",
                    ),
                ),
                (
                    "holiday_surcharge_pct",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("100"),
                        max_digits=5,
                        verbose_name="Feiertagszuschlag (%)",
                    ),
                ),
                (
                    "cumulative_surcharges",
                    models.BooleanField(
                        default=True,
                        help_text="Mehrere Zuschläge auf dieselbe Stunde gleichzeitig zulassen.",
                        verbose_name="Zuschläge kumulieren",
                    ),
                ),
                (
                    "night_start",
                    models.TimeField(default="21:00", verbose_name="Nacht beginnt"),
                ),
                (
                    "night_end",
                    models.TimeField(default="06:00", verbose_name="Nacht endet"),
                ),
                (
                    "invoice_rhythm",
                    models.CharField(
                        choices=[
                            ("weekly", "Wöchentlich"),
                            ("monthly", "Monatlich"),
                            ("flexible", "Flexibel"),
                        ],
                        default="monthly",
                        max_length=20,
                        verbose_name="Rechnungsrhythmus",
                    ),
                ),
                (
                    "payment_term_days",
                    models.PositiveSmallIntegerField(
                        default=14, verbose_name="Zahlungsziel (Tage)"
                    ),
                ),
                (
                    "vat_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("19"),
                        max_digits=5,
                        verbose_name="Umsatzsteuersatz (%)",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contracts",
                        to="customers.customer",
                        verbose_name="Kunde",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vertrag",
                "verbose_name_plural": "Verträge",
                "ordering": ("customer", "-valid_from"),
            },
        ),
        migrations.CreateModel(
            name="SurchargeRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="erstellt am"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="geändert am"),
                ),
                ("label", models.CharField(max_length=120, verbose_name="Bezeichnung")),
                (
                    "percent",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Zuschlag (%)"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="aktiv")),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="surcharge_rules",
                        to="customers.customercontract",
                        verbose_name="Vertrag",
                    ),
                ),
            ],
            options={
                "verbose_name": "Spezialzuschlag",
                "verbose_name_plural": "Spezialzuschläge",
            },
        ),
        migrations.CreateModel(
            name="TravelCostRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="erstellt am"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="geändert am"),
                ),
                (
                    "enabled",
                    models.BooleanField(default=True, verbose_name="Fahrkosten aktiv"),
                ),
                (
                    "rate_per_km",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.30"),
                        max_digits=6,
                        verbose_name="Kilometerpauschale (€/km)",
                    ),
                ),
                (
                    "round_trip",
                    models.BooleanField(
                        default=True, verbose_name="Hin- und Rückfahrt"
                    ),
                ),
                (
                    "min_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="Mindestpauschale (€)",
                    ),
                ),
                (
                    "max_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="Maximalbetrag (€)",
                    ),
                ),
                (
                    "show_on_invoice",
                    models.BooleanField(
                        default=True, verbose_name="auf Rechnung ausweisen"
                    ),
                ),
                (
                    "contract",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="travel_cost_rule",
                        to="customers.customercontract",
                        verbose_name="Vertrag",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fahrkostenregel",
                "verbose_name_plural": "Fahrkostenregeln",
            },
        ),
        migrations.CreateModel(
            name="TravelDistance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="erstellt am"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="geändert am"),
                ),
                (
                    "one_way_km",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=7,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="Entfernung einfach (km)",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="travel_distances",
                        to="customers.customer",
                        verbose_name="Kunde",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="travel_distances",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Mitarbeiter",
                    ),
                ),
            ],
            options={
                "verbose_name": "Entfernung",
                "verbose_name_plural": "Entfernungen",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("employee", "customer"),
                        name="unique_employee_customer_distance",
                    )
                ],
            },
        ),
    ]
