# Generated by Django 5.1.4 on 2026-06-15 15:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customercontract",
            name="night_end",
            field=models.TimeField(
                default=datetime.time(6, 0), verbose_name="Nacht endet"
            ),
        ),
        migrations.AlterField(
            model_name="customercontract",
            name="night_start",
            field=models.TimeField(
                default=datetime.time(20, 0), verbose_name="Nacht beginnt"
            ),
        ),
    ]
