# Generated by Django 5.1.4 on 2026-06-15 21:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='geändert am')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('slug', models.SlugField(max_length=60, unique=True, verbose_name='Kürzel')),
                ('is_active', models.BooleanField(default=True, verbose_name='aktiv')),
                ('legal_name', models.CharField(blank=True, help_text="Vollständiger Firmenname für den Rechnungskopf. Fällt auf 'Name' zurück, wenn leer.", max_length=200, verbose_name='Firmenname (rechtlich)')),
                ('street', models.CharField(blank=True, max_length=200, verbose_name='Straße')),
                ('zip_code', models.CharField(blank=True, max_length=10, verbose_name='PLZ')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='Ort')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='Telefonnummer')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-Mail-Adresse')),
                ('vat_id', models.CharField(blank=True, max_length=30, verbose_name='USt-IdNr.')),
                ('tax_number', models.CharField(blank=True, max_length=30, verbose_name='Steuernummer')),
                ('bank_name', models.CharField(blank=True, max_length=120, verbose_name='Bank')),
                ('iban', models.CharField(blank=True, max_length=40, verbose_name='IBAN')),
                ('bic', models.CharField(blank=True, max_length=20, verbose_name='BIC')),
                ('logo', models.ImageField(blank=True, help_text='Wird im Rechnungskopf angezeigt.', null=True, upload_to='org_logos/', verbose_name='Logo')),
                ('invoice_number_prefix', models.CharField(default='RECH', max_length=12, verbose_name='Rechnungsnummern-Präfix')),
                ('invoice_sequence_counter', models.PositiveIntegerField(default=0, help_text='Letzte vergebene laufende Nummer dieser Organisation.', validators=[django.core.validators.MinValueValidator(0)], verbose_name='aktueller Rechnungszähler')),
            ],
            options={
                'verbose_name': 'Organisation',
                'verbose_name_plural': 'Organisationen',
                'ordering': ('name',),
            },
        ),
    ]
