# Generated by Django 5.1.4 on 2026-06-16 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_default_org_and_backfill'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='is_small_business',
            field=models.BooleanField(default=False, help_text='Wenn aktiviert, wird auf Rechnungen keine Umsatzsteuer ausgewiesen und der gesetzliche Hinweis nach § 19 UStG aufgedruckt.', verbose_name='Kleinunternehmer (§ 19 UStG)'),
        ),
    ]
